[package]
name = "tiny-renderer-rs"
version = "0.1.0"
authors = ["Cp_Shen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = "0.1.11"
image = "0.22.3"
cgmath = "0.17.0"
gl = "0.14.0"
glfw = "0.34.0"
